[package]
name = "RustML"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
#tensorflow = "0.20.0"
ndarray = "0.15.6"